# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: risk-accept Image Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
  API_URL: ${{ vars.API_URL }}
  MAX_DAYS: ${{ vars.MAX_DAYS }}
  RISKS_CSV: ${{ vars.RISKS_CSV }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --build-arg SECURE_API_TOKEN=${{ env.SECURE_API_TOKEN }} \
        --build-arg MAX_DAYS=${{ env.MAX_DAYS }} \
        --build-arg RISKS_CSV=${{ env.RISKS_CSV }} \
        --build-arg API_URL=${{ env.API_URL }} \
        --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Log in to the Container registry
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
    
    - name: Push the Docker image
      run: |
        docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
